Converter Class Reference
Header of class Converter.
#include `/src/Converter.cpp`
Public Member Functions
Converter ()=default
Default constructor.
Converter (const cv::Mat &, bool)
Main constructor.
void setParams (uint8_t, double)
Setter for parameters for pixel comparing.
void setDebug (bool)
Setter for Debug.
void setBaseImg (const cv::Mat &)
Setter for base Image.
cv::Mat getMaskImg ()
Getter - Returns 'maskImg' content.
void showMaskImg ()
Shows Image in Window.
void resetMaskImg ()
Reset Mask image to initial state.
void setPoint (const cv::Point &)
Set Pixel point to be processed by main function.
bool findRegion ()
Main function for finding the contiguous region.
Private Member Functions
bool checkPxPos (int pxRow, int pxCol)
Check the position of the pixel at hand; whether it is inside of image borders or not.
bool checkPxMask (int pxRow, int pxCol)
Check the value of the current pixel on the mask - have we already checked it or not.
bool checkPxColor (int pxRow, int pxCol)
Check the color value of the current pixel.
double calcPixelDistance (const cv::Vec3b &px2Comp, const cv::Vec3b &initPx, uint8_t distType)
Main method which calculates the distance between pixels.
Private Attributes
cv::Mat baseImg
Private variable, contains input test image.
cv::Mat maskImg
Private variable, contains obtained mask image.
cv::Point pxPos
Private variable, contains position of pixel selected by user.
cv::Vec3b pxVal
Private variable, contains the color values of pixel selected by user.
bool debug = DefParams::DEBUG
Private variable, whether output debug info or not.
uint8_t clDistType
Private variable, contains inputed type of the color distance to be applied.
double clDistThr
Private variable, contains inputed threshold value of the chosen color distance.
Detailed Description
Header of class Converter.
Class calculates the contiguous region and converts it to the binary (mask) image.
Definition at line 15 of file Converter.h.
Constructor & Destructor Documentation
Converter() [1/2]
Converter::Converter () [default]
Default constructor.
Converter() [2/2]
Converter::Converter (const cv::Mat & _img, bool _debug = false)
Main constructor.
Constructor of the class.
Parameters
_img - input test color image
_debug - debug information switcher
Definition at line 19 of file Converter.cpp.
References baseImg, and maskImg.
Member Function Documentation
calcPixelDistance()
double Converter::calcPixelDistance (const cv::Vec3b & px2Comp, const cv::Vec3b & initPx, uint8_t distType) [private]
Main method which calculates the distance between pixels.
Definition at line 188 of file Converter.cpp.
References debug, DefParams::FR256, DefParams::K1, DefParams::K2, DefParams::k_L, and DefParams::SL.
Referenced by checkPxColor().
checkPxColor()
bool Converter::checkPxColor (int pxRow, int pxCol) [private]
Check the color value of the current pixel.
Definition at line 166 of file Converter.cpp.
References baseImg, calcPixelDistance(), clDistThr, clDistType, debug, maskImg, and pxVal.
Referenced by findRegion().
checkPxMask()
bool Converter::checkPxMask (int pxRow, int pxCol) [private]
Check the value of the current pixel on the mask - have we already checked it or not.
Definition at line 150 of file Converter.cpp.
References debug, and maskImg.
Referenced by findRegion().
checkPxPos()
bool Converter::checkPxPos (int pxRow, int pxCol) [private]
Check the position of the pixel at hand; whether it is inside of image borders or not.
Definition at line 135 of file Converter.cpp.
References baseImg, and debug.
Referenced by findRegion().
findRegion()
bool Converter::findRegion ()
Main function for finding the contiguous region.
FindRegion function - the main one.
Definition at line 88 of file Converter.cpp.
References checkPxColor(), checkPxMask(), checkPxPos(), maskImg, and pxPos.
Referenced by Visualizer::mCallback().
getMaskImg()
cv::Mat Converter::getMaskImg ()
Getter - Returns 'maskImg' content.
Definition at line 56 of file Converter.cpp.
References maskImg.
Referenced by Visualizer::getMaskImg().
resetMaskImg()
void Converter::resetMaskImg ()
Reset Mask image to initial state.
Definition at line 62 of file Converter.cpp.
References baseImg, and maskImg.
Referenced by Visualizer::mCallback().
setBaseImg()
void Converter::setBaseImg (const cv::Mat & _baseImg)
Setter for base Image.
Getter - Returns 'maskImg' content.
Definition at line 49 of file Converter.cpp.
References baseImg, and maskImg.
Referenced by Visualizer::startProcessing().
setDebug()
void Converter::setDebug (bool _debug)
Setter for Debug.
Setter for 'debug' parameter.
Definition at line 26 of file Converter.cpp.
References debug.
setParams()
void Converter::setParams (uint8_t _clDistType, double _clDistThr)
Setter for parameters for pixel comparing.
Definition at line 32 of file Converter.cpp.
References baseImg, clDistThr, and clDistType.
Referenced by Visualizer::startProcessing().
setPoint()
void Converter::setPoint (const cv::Point & _pxPos)
Set Pixel point to be processed by main function.
Definition at line 78 of file Converter.cpp.
References baseImg, debug, pxPos, and pxVal.
Referenced by Visualizer::mCallback().
showMaskImg()
void Converter::showMaskImg ()
Shows Image in Window.
Definition at line 68 of file Converter.cpp.
References maskImg.
Referenced by Visualizer::mCallback(), and Visualizer::showMaskImg().
Member Data Documentation
baseImg
cv::Mat Converter::baseImg [private]
Private variable, contains input test image.
Definition at line 19 of file Converter.h.
Referenced by checkPxColor(), checkPxPos(), Converter(), resetMaskImg(), setBaseImg(), setParams(), and setPoint().
clDistThr
double Converter::clDistThr [private]
Private variable, contains inputed threshold value of the chosen color distance.
Definition at line 31 of file Converter.h.
Referenced by checkPxColor(), and setParams().
clDistType
uint8_t Converter::clDistType [private]
Private variable, contains inputed type of the color distance to be applied.
Definition at line 29 of file Converter.h.
Referenced by checkPxColor(), and setParams().
debug
bool Converter::debug = DefParams::DEBUG [private]
Private variable, whether output debug info or not.
Definition at line 27 of file Converter.h.
Referenced by calcPixelDistance(), checkPxColor(), checkPxMask(), checkPxPos(), setDebug(), and setPoint().
maskImg
cv::Mat Converter::maskImg [private]
Private variable, contains obtained mask image.
Definition at line 21 of file Converter.h.
Referenced by checkPxColor(), checkPxMask(), Converter(), findRegion(), getMaskImg(), resetMaskImg(), setBaseImg(), and showMaskImg().
pxPos
cv::Point Converter::pxPos [private]
Private variable, contains position of pixel selected by user.
Definition at line 23 of file Converter.h.
Referenced by findRegion(), and setPoint().
pxVal
cv::Vec3b Converter::pxVal [private]
Private variable, contains the color values of pixel selected by user.
Definition at line 25 of file Converter.h.
Referenced by checkPxColor(), and setPoint().
The documentation for this class was generated from the following files:
src/Converter.h
src/Converter.cpp