Visualizer Class Reference
Displays the test image as well as calculated image binary mask.
#include `/scr/Visualizer.cpp`
Public Member Functions
Visualizer (const std::string &_fName)
Constructor of the class.
bool readBaseImg ()
Methods reads test (base) image using its filename and shows it in window.
cv::Mat getBaseImg ()
Getter for test (base) image.
bool showBaseImg ()
Visualize the test (base) image in a window.
cv::Mat getMaskImg ()
Getter for mask (binary, output) image.
bool showMaskImg ()
Visualize the mask (binary, output) image in a window.
bool startProcessing (uint8_t, double)
Main function of the utility.
void mCallback (int, int)
One of the main functions of the utility.
Static Public Member Functions
static void mCallback_Func (int, int, int, int, void *)
One of the main functions of the utility.
Private Attributes
std::string fName
Private variable, contains input test image filename.
cv::Mat baseImg
Private variable, contains input test image.
Converter convObj
Private variable, contains Converter object.
Detailed Description
Displays the test image as well as calculated image binary mask.
Class displays the test image as well as calculated image binary mask
Definition at line 16 of file Visualizer.h.
Constructor & Destructor Documentation
Visualizer()
Visualizer::Visualizer (const std::string & _fName)
Constructor of the class.
Parameters
_fName - filename of the input test color image
Definition at line 17 of file Visualizer.cpp.
Member Function Documentation
getBaseImg()
cv::Mat Visualizer::getBaseImg ()
Getter for test (base) image.
Definition at line 43 of file Visualizer.cpp.
References baseImg.
getMaskImg()
cv::Mat Visualizer::getMaskImg ()
Getter for mask (binary, output) image.
Definition at line 61 of file Visualizer.cpp.
References convObj, and Converter::getMaskImg().
Referenced by main().
mCallback()
void Visualizer::mCallback (int x, int y)
One of the main functions of the utility.
Parameters
x - X coordinate of mouse position in the window while clicking
y - Y coordinate of mouse position in the window while clicking
Definition at line 114 of file Visualizer.cpp.
References convObj, DefParams::DEBUG, Converter::findRegion(), Converter::resetMaskImg(), Converter::setPoint(), and Converter::showMaskImg().
mCallback_Func()
void Visualizer::mCallback_Func (int event, int x, int y, int flag, void * param) [static]
One of the main functions of the utility.
Parameters
event - the type of the mouse activity, int
x - X coordinate of mouse position in the window while clicking
y - Y coordinate of mouse position in the window while clicking
flag - flag parameter (didn't use it)
param - pointer for transferring user data if necessary (used it to send the pointer to the Visualizer-object)
Definition at line 98 of file Visualizer.cpp.
Referenced by startProcessing().
readBaseImg()
bool Visualizer::readBaseImg ()
Methods reads test (base) image using its filename and shows it in window.
Definition at line 23 of file Visualizer.cpp.
References baseImg, and fName.
Referenced by main().
showBaseImg()
bool Visualizer::showBaseImg ()
Visualize the test (base) image in a window.
Definition at line 49 of file Visualizer.cpp.
References baseImg.
Referenced by main().
showMaskImg()
bool Visualizer::showMaskImg ()
Visualize the mask (binary, output) image in a window.
Definition at line 67 of file Visualizer.cpp.
References convObj, and Converter::showMaskImg().
startProcessing()
bool Visualizer::startProcessing (uint8_t clDistType, double clDistThr)
Main function of the utility.
Parameters
clDistType - type of the color distance to be applied
clDistThr - threshold value for the color distance to be applied
Definition at line 78 of file Visualizer.cpp.
References baseImg, convObj, mCallback_Func(), Converter::setBaseImg(), and Converter::setParams().
Referenced by main().
Member Data Documentation
baseImg
cv::Mat Visualizer::baseImg [private]
Private variable, contains input test image.
Definition at line 22 of file Visualizer.h.
Referenced by getBaseImg(), readBaseImg(), showBaseImg(), and startProcessing().
convObj
Converter Visualizer::convObj [private]
Private variable, contains Converter object.
Definition at line 24 of file Visualizer.h.
Referenced by getMaskImg(), mCallback(), showMaskImg(), and startProcessing().
fName
std::string Visualizer::fName [private]
Private variable, contains input test image filename.
Definition at line 20 of file Visualizer.h.
Referenced by readBaseImg().
The documentation for this class was generated from the following files:
src/Visualizer.h
src/Visualizer.cpp